### ISSUE TITLE
Code Project - Form checkboxes yields String value instead of Boolean value

### ISSUE THREAD

**Issue by nelsontran** [ChristianMurphy/nicest#435]
If no value attribute is given to an HTML checkbox element, the value sent in a form submission defaults to `"on"`. This is a problem in the `code-project` recipe, particularly in the "Choose Issue Tracker" step, where a Boolean value is expected.

![Choose Issue Tracker](https://cloud.githubusercontent.com/assets/10904556/22667233/2d8fc69c-ec79-11e6-89bb-7f47de21880d.png)

Clicking on the next button with these options yields the following response:

`{"statusCode":400,"error":"Bad Request","message":"child \"hasBacklog\" fails because [\"hasBacklog\" must be a boolean]","validation":{"source":"payload","keys":["hasBacklog"]}}`

Using Chromium's developer tools, we can see the values that the form is submitting.

![POST Data](https://cloud.githubusercontent.com/assets/10904556/22667310/7d693af4-ec79-11e6-88ad-2a09c021a8b3.png)

**Comment by ChristianMurphy** [comment]
I think Joi switched off truthy and falsy by default. On and Off would need to be added to the validations manually.
https://github.com/hapijs/joi/blob/master/API.md#boolean
